### ISSUE TITLE
A header file is missing: pure_pursuit/PurePursuitPlannerConfig.h

### ISSUE THREAD

**Issue by HsiaoRay** [raphaelkba/pure_pursuit#1]
Hi, I found your work fascinating, but when I ran the plugin, the compilation failed, showing a missing file: pure_pursuit/PurePursuitPlannerConfig.h . Have you forgotten? Could you please check and upload it again?Thank you.
Have a nice day

**Comment by HsiaoRay** [comment]
I have found it, thanks for your trouble.

**Comment by chanzw** [comment]
> 
> 
> I have found it, thanks for your trouble.

hello,how do you find it? Can you tell me ? thanks

**Comment by chanzw** [comment]
Hello,I have the same problem about pure_pursuit/PurePursuitPlannerConfig.h. It shows as a missing file. Thanks
